### ISSUE TITLE
bug: Analfabeto

### ISSUE THREAD

**Issue by snek0070** [nekoraw/bancho.py#14]
### Describe the bug

Quando se abre uma partida online no servidor, aparece a mensagem "Acesse o **históico** da partida"

### To Reproduce

1. Abrir uma partida online no Fubica.

### Expected behavior

Aparecer a mensagem: "Acesse o **históico** da partida"

### bancho.py Version

A mais recente

### Python Version

3.9.X (Default)

### Additional context

nekoraw analfabetoKKKKKKK

**Comment by floccini** [comment]
MT BURRO PQP

**Comment by OKakirM** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by nekoraw** [comment]
arrumado em https://github.com/nekoraw/bancho.py/commit/919013bb1e0a29411e229981e83182531164a6e9.
vai aparecer no server de produção em breve (tem gente jogando multiplayer e n quero atrapalhar)
